### ISSUE TITLE
 Error: The `libsass` binding was not found on gulp-sass

### ISSUE THREAD

**Issue by kaave** [ali-inc/ubuntu15.04-elixir#4]
gulpでgulp-sassを利用してsassをコンパイルすると以下のエラー

```
Error: The `libsass` binding was not found in /home/vagrant/gulp_phoenix/node_modules/node-sass/vendor/linu
x-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (/home/vagrant/gulp_phoenix/node_modules/node-sass/lib/extensions.js:158:11)
    at Object.<anonymous> (/home/vagrant/gulp_phoenix/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vagrant/gulp_phoenix/node_modules/babel-core/nod
e_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/vagrant/gulp_phoenix/node_modules/gulp-sass/index.js:176:21)
```

libsassのインストールが必要？

**Comment by kaave** [comment]
以下を参考にコマンドがしがし叩きましたがメモリ不足エラーで死亡したので諦めました

[https://gist.github.com/edouard-lopez/503d40a5c1a49cf8ae87]()

**Comment by kaave** [comment]
気がついたらsassコンパイルできるようになったので閉じておきます
